from enum import StrEnum


class ActiveStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class DestinationType(StrEnum):
    FREE_CHANNEL = "FREE_CHANNEL"
    VIP_FORUM = "VIP_FORUM"
    VAULT_CHANNEL = "VAULT_CHANNEL"
    ADMIN_ALERT_CHAT = "ADMIN_ALERT_CHAT"


class DestinationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    OFFLINE = "OFFLINE"


class TopicRole(StrEnum):
    CONTENT = "CONTENT"
    GENERAL = "GENERAL"
    REQUESTS = "REQUESTS"


class PlanKind(StrEnum):
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    LIFETIME = "LIFETIME"
    CUSTOM = "CUSTOM"


class OfferKind(StrEnum):
    DISCOUNT = "DISCOUNT"
    ADD_ON = "ADD_ON"
    BUNDLE = "BUNDLE"
    UPGRADE = "UPGRADE"
    WINBACK = "WINBACK"


class LeadState(StrEnum):
    NEW = "NEW"
    AGE_CONFIRMED = "AGE_CONFIRMED"
    INTENT_VIP = "INTENT_VIP"
    INTENT_FREE = "INTENT_FREE"
    PRODUCT_VIEWED = "PRODUCT_VIEWED"
    PLAN_SELECTED = "PLAN_SELECTED"
    CHECKOUT_STARTED = "CHECKOUT_STARTED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_ABANDONED = "PAYMENT_ABANDONED"
    PAID = "PAID"
    ACCESS_PENDING = "ACCESS_PENDING"
    CUSTOMER_ACTIVE = "CUSTOMER_ACTIVE"
    UPSELL_ELIGIBLE = "UPSELL_ELIGIBLE"
    EXPIRED_CUSTOMER = "EXPIRED_CUSTOMER"
    WINBACK_ELIGIBLE = "WINBACK_ELIGIBLE"


class CopySlotKey(StrEnum):
    BOT_HERO = "BOT_HERO"
    FREE_CTA = "FREE_CTA"
    VIP_CTA = "VIP_CTA"
    CHECKOUT_RECOVERY = "CHECKOUT_RECOVERY"
    POST_PURCHASE_UPSELL = "POST_PURCHASE_UPSELL"
    WINBACK = "WINBACK"
    ACCESS_GRANTED = "ACCESS_GRANTED"
    ACCESS_EXPIRED = "ACCESS_EXPIRED"
    FREE_POST_CAPTION = "FREE_POST_CAPTION"
    VIP_PACK_CAPTION = "VIP_PACK_CAPTION"


class MediaType(StrEnum):
    VIDEO = "VIDEO"
    IMAGE = "IMAGE"
    GIF = "GIF"


class AssetStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    SELECTED = "SELECTED"
    ACQUIRING = "ACQUIRING"
    LOCAL_READY = "LOCAL_READY"
    VAULTED = "VAULTED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    PURGED = "PURGED"


class CandidateStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ACQUIRING = "ACQUIRING"
    READY = "READY"
    ARCHIVED = "ARCHIVED"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEFERRED = "DEFERRED"


class DuplicateClassification(StrEnum):
    NEW = "NEW"
    SAME_SOURCE_ITEM = "SAME_SOURCE_ITEM"
    SAME_SHA256 = "SAME_SHA256"


class PackStatus(StrEnum):
    REVIEW = "REVIEW"
    READY = "READY"
    REJECTED = "REJECTED"


class PublicationTarget(StrEnum):
    FREE = "FREE"
    VIP = "VIP"


class PublicationStatus(StrEnum):
    QUEUED = "QUEUED"
    SCHEDULED = "SCHEDULED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class PublicationPlanStatus(StrEnum):
    PLANNED = "PLANNED"
    SKIPPED_NO_CONTENT = "SKIPPED_NO_CONTENT"
    SKIPPED_CONFIGURATION = "SKIPPED_CONFIGURATION"


class OrderStatus(StrEnum):
    CREATED = "CREATED"
    CHECKOUT_READY = "CHECKOUT_READY"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAID = "PAID"
    ACCESS_PENDING = "ACCESS_PENDING"
    FULFILLED = "FULFILLED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class PaymentStatus(StrEnum):
    CREATED = "CREATED"
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    REFUNDED = "REFUNDED"
    DUPLICATE_REVIEW = "DUPLICATE_REVIEW"


class EntitlementStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"
    SUSPENDED = "SUSPENDED"


class MembershipStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    REMOVED = "REMOVED"
    FAILED = "FAILED"


class JobType(StrEnum):
    DISCOVER_SOURCE = "DISCOVER_SOURCE"
    ACQUIRE_MEDIA = "ACQUIRE_MEDIA"
    PROBE_MEDIA = "PROBE_MEDIA"
    GENERATE_PREVIEW = "GENERATE_PREVIEW"
    UPLOAD_VAULT = "UPLOAD_VAULT"
    PUBLISH_CONTENT = "PUBLISH_CONTENT"
    REFRESH_METRICS = "REFRESH_METRICS"
    RECHECK_PAYMENT = "RECHECK_PAYMENT"
    FULFILL_ACCESS = "FULFILL_ACCESS"
    EXPIRE_ACCESS = "EXPIRE_ACCESS"
    REPAIR_MEMBERSHIP = "REPAIR_MEMBERSHIP"
    CLEAN_LOCAL_MEDIA = "CLEAN_LOCAL_MEDIA"
    SEND_SALES_FOLLOWUP = "SEND_SALES_FOLLOWUP"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class Severity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class ModerationSeverity(StrEnum):
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"
    REMOVE = "REMOVE"
    BAN_REVIEW = "BAN_REVIEW"
