"""initial domain schema

Revision ID: ef39cde4b9c4
Revises: 
Create Date: 2026-08-28 10:24:24.380547
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ef39cde4b9c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_code'), 'alerts', ['code'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('content_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_content_tags_slug'), 'content_tags', ['slug'], unique=True)
    op.create_table('copy_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_slots_key'), 'copy_slots', ['key'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('age_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_telegram_user_id'), 'customers', ['telegram_user_id'], unique=True)
    op.create_table('integration_credentials_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('integration', sa.String(length=80), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('secret_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_owner', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=180), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_jobs_run_after'), 'jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('moderation_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('whole_word', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niches_slug'), 'niches', ['slug'], unique=True)
    op.create_table('offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('communities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('niche_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_communities_niche_id'), 'communities', ['niche_id'], unique=False)
    op.create_table('customer_telegram_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_telegram_identities_customer_id'), 'customer_telegram_identities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_telegram_identities_telegram_user_id'), 'customer_telegram_identities', ['telegram_user_id'], unique=True)
    op.create_table('microniches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('niche_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('niche_id', 'slug', name='uq_microniche_niche_slug')
    )
    op.create_index(op.f('ix_microniches_niche_id'), 'microniches', ['niche_id'], unique=False)
    op.create_table('offer_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('condition_type', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_conditions_offer_id'), 'offer_conditions', ['offer_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=False),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('default_niche_id', sa.String(length=36), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('approval_count', sa.Integer(), nullable=False),
    sa.Column('presented_count', sa.Integer(), nullable=False),
    sa.Column('published_count', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('promise_snapshot', sa.JSON(), nullable=False),
    sa.Column('active_for_sale', sa.Boolean(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'version', name='uq_community_version')
    )
    op.create_index(op.f('ix_community_versions_community_id'), 'community_versions', ['community_id'], unique=False)
    op.create_table('content_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_item_id', sa.String(length=255), nullable=False),
    sa.Column('source_collection_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_item_id', name='uq_candidate_source_item')
    )
    op.create_index(op.f('ix_content_candidates_source_id'), 'content_candidates', ['source_id'], unique=False)
    op.create_index(op.f('ix_content_candidates_source_item_id'), 'content_candidates', ['source_item_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_charge_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('checkout_payload', sa.JSON(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_charge_id', name='uq_payment_provider_charge')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('source_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('locator', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'locator', name='uq_source_profile_locator')
    )
    op.create_index(op.f('ix_source_profiles_source_id'), 'source_profiles', ['source_id'], unique=False)
    op.create_table('telegram_destinations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('community_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('destination_type', sa.String(length=32), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('replacement_destination_id', sa.String(length=36), nullable=True),
    sa.Column('protected_content', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['replacement_destination_id'], ['telegram_destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_destinations_community_id'), 'telegram_destinations', ['community_id'], unique=False)
    op.create_index(op.f('ix_telegram_destinations_telegram_chat_id'), 'telegram_destinations', ['telegram_chat_id'], unique=True)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=True),
    sa.Column('microniche_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['content_candidates.id'], ),
    sa.ForeignKeyConstraint(['microniche_id'], ['microniches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_candidate_id'), 'approvals', ['candidate_id'], unique=False)
    op.create_table('community_version_microniches',
    sa.Column('community_version_id', sa.String(length=36), nullable=False),
    sa.Column('microniche_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['community_version_id'], ['community_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['microniche_id'], ['microniches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_version_id', 'microniche_id')
    )
    op.create_table('content_packs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('content_score', sa.Float(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['content_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_packs_candidate_id'), 'content_packs', ['candidate_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('source_locator', sa.Text(), nullable=True),
    sa.Column('mime', sa.String(length=120), nullable=True),
    sa.Column('extension', sa.String(length=16), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('source_caption', sa.Text(), nullable=True),
    sa.Column('source_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thumbnail_ref', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('telegram_file_id', sa.Text(), nullable=True),
    sa.Column('telegram_file_unique_id', sa.String(length=255), nullable=True),
    sa.Column('vault_message_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['content_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_candidate_id'), 'media_assets', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_media_assets_sha256'), 'media_assets', ['sha256'], unique=False)
    op.create_index(op.f('ix_media_assets_telegram_file_unique_id'), 'media_assets', ['telegram_file_unique_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_event_id', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_payment_event_external')
    )
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('community_version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_version_id'], ['community_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_community_version_id'), 'products', ['community_version_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('microniche_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('message_thread_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['telegram_destinations.id'], ),
    sa.ForeignKeyConstraint(['microniche_id'], ['microniches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'message_thread_id', name='uq_topic_thread')
    )
    op.create_index(op.f('ix_topics_destination_id'), 'topics', ['destination_id'], unique=False)
    op.create_index(op.f('ix_topics_microniche_id'), 'topics', ['microniche_id'], unique=False)
    op.create_table('content_pack_microniches',
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('microniche_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['microniche_id'], ['microniches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['content_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pack_id', 'microniche_id')
    )
    op.create_table('content_pack_tags',
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['content_packs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['content_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pack_id', 'tag_id')
    )
    op.create_table('copy_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('media_asset_id', sa.String(length=36), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['copy_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_variants_product_id'), 'copy_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_copy_variants_slot_id'), 'copy_variants', ['slot_id'], unique=False)
    op.create_table('derivatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_asset_id', sa.String(length=36), nullable=False),
    sa.Column('derived_asset_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['derived_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derived_asset_id')
    )
    op.create_index(op.f('ix_derivatives_source_asset_id'), 'derivatives', ['source_asset_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('last_product_id', sa.String(length=36), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['last_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=True)
    op.create_table('moderation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=True),
    sa.Column('destination_id', sa.String(length=36), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('matched_rule_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['telegram_destinations.id'], ),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['moderation_rules.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_events_telegram_user_id'), 'moderation_events', ['telegram_user_id'], unique=False)
    op.create_table('offer_products',
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'product_id')
    )
    op.create_table('pack_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('derivative_of_asset_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['derivative_of_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['content_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id', 'position', name='uq_pack_position')
    )
    op.create_index(op.f('ix_pack_items_asset_id'), 'pack_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_pack_items_pack_id'), 'pack_items', ['pack_id'], unique=False)
    op.create_table('price_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('lifetime', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_plans_product_id'), 'price_plans', ['product_id'], unique=False)
    op.create_table('publication_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('microniche_id', sa.String(length=36), nullable=True),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('posts_per_day', sa.Integer(), nullable=False),
    sa.Column('randomize_within_window', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['telegram_destinations.id'], ),
    sa.ForeignKeyConstraint(['microniche_id'], ['microniches.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_rules_destination_id'), 'publication_rules', ['destination_id'], unique=False)
    op.create_index(op.f('ix_publication_rules_microniche_id'), 'publication_rules', ['microniche_id'], unique=False)
    op.create_index(op.f('ix_publication_rules_topic_id'), 'publication_rules', ['topic_id'], unique=False)
    op.create_table('vault_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('telegram_message_id', sa.String(length=64), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_id'], ['telegram_destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', name='uq_vault_asset')
    )
    op.create_index(op.f('ix_vault_objects_asset_id'), 'vault_objects', ['asset_id'], unique=False)
    op.create_index(op.f('ix_vault_objects_destination_id'), 'vault_objects', ['destination_id'], unique=False)
    op.create_table('lead_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_events_event_type'), 'lead_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_lead_events_lead_id'), 'lead_events', ['lead_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('price_plan_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_plan_id'], ['price_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_price_plan_id'), 'order_items', ['price_plan_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('publication_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['telegram_destinations.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['content_packs.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['publication_rules.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_jobs_destination_id'), 'publication_jobs', ['destination_id'], unique=False)
    op.create_index(op.f('ix_publication_jobs_pack_id'), 'publication_jobs', ['pack_id'], unique=False)
    op.create_index(op.f('ix_publication_jobs_rule_id'), 'publication_jobs', ['rule_id'], unique=False)
    op.create_index(op.f('ix_publication_jobs_scheduled_for'), 'publication_jobs', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_publication_jobs_topic_id'), 'publication_jobs', ['topic_id'], unique=False)
    op.create_table('schedule_windows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publication_rule_id', sa.String(length=36), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_rule_id'], ['publication_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_windows_publication_rule_id'), 'schedule_windows', ['publication_rule_id'], unique=False)
    op.create_table('entitlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('community_version_id', sa.String(length=36), nullable=False),
    sa.Column('price_plan_id', sa.String(length=36), nullable=False),
    sa.Column('source_order_item_id', sa.String(length=36), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_version_id'], ['community_versions.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['price_plan_id'], ['price_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_order_item_id', name='uq_entitlement_order_item')
    )
    op.create_index(op.f('ix_entitlements_community_version_id'), 'entitlements', ['community_version_id'], unique=False)
    op.create_index(op.f('ix_entitlements_customer_id'), 'entitlements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_entitlements_expires_at'), 'entitlements', ['expires_at'], unique=False)
    op.create_index(op.f('ix_entitlements_product_id'), 'entitlements', ['product_id'], unique=False)
    op.create_index(op.f('ix_entitlements_status'), 'entitlements', ['status'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publication_job_id', sa.String(length=36), nullable=False),
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('telegram_message_ids', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('copy_variant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['copy_variant_id'], ['copy_variants.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['telegram_destinations.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['content_packs.id'], ),
    sa.ForeignKeyConstraint(['publication_job_id'], ['publication_jobs.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_job_id', name='uq_publication_job_once')
    )
    op.create_index(op.f('ix_publications_destination_id'), 'publications', ['destination_id'], unique=False)
    op.create_index(op.f('ix_publications_pack_id'), 'publications', ['pack_id'], unique=False)
    op.create_index(op.f('ix_publications_topic_id'), 'publications', ['topic_id'], unique=False)
    op.create_table('membership_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entitlement_id', sa.String(length=36), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['telegram_destinations.id'], ),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entitlement_id', 'destination_id', name='uq_membership_entitlement_dest')
    )
    op.create_index(op.f('ix_membership_grants_destination_id'), 'membership_grants', ['destination_id'], unique=False)
    op.create_index(op.f('ix_membership_grants_entitlement_id'), 'membership_grants', ['entitlement_id'], unique=False)
    op.create_index(op.f('ix_membership_grants_telegram_user_id'), 'membership_grants', ['telegram_user_id'], unique=False)
    op.create_table('publication_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('reactions', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('unique_repliers', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', name='uq_publication_metric')
    )
    op.create_table('invite_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('membership_grant_id', sa.String(length=36), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=True),
    sa.Column('join_request', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membership_grant_id'], ['membership_grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_records_membership_grant_id'), 'invite_records', ['membership_grant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_records_membership_grant_id'), table_name='invite_records')
    op.drop_table('invite_records')
    op.drop_table('publication_metrics')
    op.drop_index(op.f('ix_membership_grants_telegram_user_id'), table_name='membership_grants')
    op.drop_index(op.f('ix_membership_grants_entitlement_id'), table_name='membership_grants')
    op.drop_index(op.f('ix_membership_grants_destination_id'), table_name='membership_grants')
    op.drop_table('membership_grants')
    op.drop_index(op.f('ix_publications_topic_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_pack_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_destination_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_entitlements_status'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_product_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_expires_at'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_customer_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_community_version_id'), table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index(op.f('ix_schedule_windows_publication_rule_id'), table_name='schedule_windows')
    op.drop_table('schedule_windows')
    op.drop_index(op.f('ix_publication_jobs_topic_id'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_scheduled_for'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_rule_id'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_pack_id'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_destination_id'), table_name='publication_jobs')
    op.drop_table('publication_jobs')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_price_plan_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_lead_events_lead_id'), table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_event_type'), table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_index(op.f('ix_vault_objects_destination_id'), table_name='vault_objects')
    op.drop_index(op.f('ix_vault_objects_asset_id'), table_name='vault_objects')
    op.drop_table('vault_objects')
    op.drop_index(op.f('ix_publication_rules_topic_id'), table_name='publication_rules')
    op.drop_index(op.f('ix_publication_rules_microniche_id'), table_name='publication_rules')
    op.drop_index(op.f('ix_publication_rules_destination_id'), table_name='publication_rules')
    op.drop_table('publication_rules')
    op.drop_index(op.f('ix_price_plans_product_id'), table_name='price_plans')
    op.drop_table('price_plans')
    op.drop_index(op.f('ix_pack_items_pack_id'), table_name='pack_items')
    op.drop_index(op.f('ix_pack_items_asset_id'), table_name='pack_items')
    op.drop_table('pack_items')
    op.drop_table('offer_products')
    op.drop_index(op.f('ix_moderation_events_telegram_user_id'), table_name='moderation_events')
    op.drop_table('moderation_events')
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_derivatives_source_asset_id'), table_name='derivatives')
    op.drop_table('derivatives')
    op.drop_index(op.f('ix_copy_variants_slot_id'), table_name='copy_variants')
    op.drop_index(op.f('ix_copy_variants_product_id'), table_name='copy_variants')
    op.drop_table('copy_variants')
    op.drop_table('content_pack_tags')
    op.drop_table('content_pack_microniches')
    op.drop_index(op.f('ix_topics_microniche_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_destination_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_community_version_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_media_assets_telegram_file_unique_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_sha256'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_candidate_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_content_packs_candidate_id'), table_name='content_packs')
    op.drop_table('content_packs')
    op.drop_table('community_version_microniches')
    op.drop_index(op.f('ix_approvals_candidate_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_telegram_destinations_telegram_chat_id'), table_name='telegram_destinations')
    op.drop_index(op.f('ix_telegram_destinations_community_id'), table_name='telegram_destinations')
    op.drop_table('telegram_destinations')
    op.drop_index(op.f('ix_source_profiles_source_id'), table_name='source_profiles')
    op.drop_table('source_profiles')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_content_candidates_source_item_id'), table_name='content_candidates')
    op.drop_index(op.f('ix_content_candidates_source_id'), table_name='content_candidates')
    op.drop_table('content_candidates')
    op.drop_index(op.f('ix_community_versions_community_id'), table_name='community_versions')
    op.drop_table('community_versions')
    op.drop_table('sources')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_offer_conditions_offer_id'), table_name='offer_conditions')
    op.drop_table('offer_conditions')
    op.drop_index(op.f('ix_microniches_niche_id'), table_name='microniches')
    op.drop_table('microniches')
    op.drop_index(op.f('ix_customer_telegram_identities_telegram_user_id'), table_name='customer_telegram_identities')
    op.drop_index(op.f('ix_customer_telegram_identities_customer_id'), table_name='customer_telegram_identities')
    op.drop_table('customer_telegram_identities')
    op.drop_index(op.f('ix_communities_niche_id'), table_name='communities')
    op.drop_table('communities')
    op.drop_table('settings')
    op.drop_table('offers')
    op.drop_index(op.f('ix_niches_slug'), table_name='niches')
    op.drop_table('niches')
    op.drop_table('moderation_rules')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_after'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('integration_credentials_metadata')
    op.drop_index(op.f('ix_customers_telegram_user_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_copy_slots_key'), table_name='copy_slots')
    op.drop_table('copy_slots')
    op.drop_index(op.f('ix_content_tags_slug'), table_name='content_tags')
    op.drop_table('content_tags')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_code'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
